### ISSUE TITLE
Is it possible to add mob drops?

### ISSUE THREAD

**Issue by wizardsambolton** [arendjr/PlainText#10]

**Comment by arendjr** [comment]
Actually, they are already implemented :) All characters by default drop all items in their inventory when they die. In `data/scripts/gameobjects/character.js` you'll find the `Character#die()` method which implements this.

If you want to customize the behavior for specific NPCs you probably may want to use the hook into `ondie` trigger. For more information about triggers, see: https://github.com/arendjr/PlainText/wiki/Triggers
