### ISSUE TITLE
Game crashes "what(): Unknown game object type"

### ISSUE THREAD

**Issue by SkepticSarah** [arendjr/PlainText#11]
I just installed this PlainText on Debian 8 and I was loving it until it crashed saying:

terminate called after throwing an instance of 'GameException'
  what():  Unknown game object type
./run-mud.sh: line 3: 19040 Aborted                 ./PlainText

Help please I really enjoyed playing this MUD and it wont start back up again.

**Comment by SkepticSarah** [comment]
Nevermind, found out that the version of qt that debian installed was out of date.  Fixed

**Comment by SkepticSarah** [comment]
I thought we had fixed the problem but apparently not because i had the same error again and it crashed the server.

**Comment by arendjr** [comment]
Hey there, are you playing the game for fun or do you intent to build a MUD with the engine? If it's the first I'm gonna have to disappoint you, the game world that's shipped is mainly for demo purposes so if you try to "play" it you will hit a wall very soon...

If you want to build your own MUD with it though, I think the engine might be a nice starting point, provided you're willing to dig in and get your hands dirty :) I haven't done anything with it for a few years, so I'm not sure what it is specifically that's causing this issue, but it sounds like a data corruption and if you were to run the engine in Qt Creator the stack trace when it crashes should quickly point you to the culprit.

Cheers!

**Comment by SkepticSarah** [comment]
Sad to hear you stopped working on Plaintext because it was really enjoyable to play with.  We did fix the issue by running the server on Ubuntu so there must be a package issue with Debian.
