### ISSUE TITLE
Don't specify -stdlib=libc++ for unix targets

### ISSUE THREAD

**Issue by Earnestly** [arendjr/PlainText#13]
Currently when used on Linux (clang++ 6.0) it will result in errors such as:

```
/usr/include/qt/QtCore/qglobal.h:45:12: fatal error: 'type_traits' file not found
#  include <type_traits>
           ^~~~~~~~~~~~~
```

and

```
src/main.cpp:1:10: fatal error: 'csignal' file not found
#include <csignal>
         ^~~~~~~~~
```

Applying the following fix solves the issue:

```diff
diff --git a/environment.pri b/environment.pri
index 3f32f35..d721c59 100644
--- a/environment.pri
+++ b/environment.pri
@@ -15,7 +15,6 @@ macx {
     system(which clang++ 2> /dev/null) {
         LIBS += -lc++
         QMAKE_CXX = clang++
-        QMAKE_CXXFLAGS = -stdlib=libc++
     }
 }
 QMAKE_CXXFLAGS += -std=c++11
```

IIRC, this use of `-stdlib` should not be necessary on MacOS Mavericks and after either.

**Comment by arendjr** [comment]
Thanks! I had to do that back when C++11 support was still flaky, but I believe you it shouldn't be necessary anymore :) I haven't honestly built the project in years though, so I cannot verify now if it really works...

**Comment by arendjr** [comment]
Doesn't seem relevant for the new Rust-based version (WIP) anymore :)
